no more per-step checks
Signed-off-by: jflo <justin+github@florentine.us>

diff --git a/.github/workflows/acceptance-tests.yml b/.github/workflows/acceptance-tests.yml
--- a/.github/workflows/acceptance-tests.yml
+++ b/.github/workflows/acceptance-tests.yml
@@ -81,30 +81,14 @@ jobs:
       matrix:
         runner_index: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
     steps:
-      - name: already tested
-        id: needsRun
-        uses: actions/github-script@v7.0.1
-        with:
-          script: |
-            const { data: { statuses } } = await github.rest.repos.getCombinedStatusForRef({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              ref: context.sha,
-            });
-            const acceptanceTested = statuses.find(({ context }) => context === 'acceptance-tests');
-            const needsRun = acceptanceTested.find(({ state }) => state != 'success' && state != 'pending');
-            return needsRun
       - name: Checkout Repo
-        if: steps.needsRun.outputs.result == 'true'
         uses: actions/checkout@v3
       - name: Set up Java
-        if: steps.needsRun.outputs.result == 'true'
         uses: actions/setup-java@v3
         with:
           distribution: adopt
           java-version: 17
       - name: get acceptance test report
-        if: steps.needsRun.outputs.result == 'true'
         uses: dawidd6/action-download-artifact@v2
         with:
           branch: main
@@ -113,10 +97,8 @@ jobs:
           path: tmp/junit-xml-reports-downloaded
           if_no_artifact_found: true
       - name: setup gradle
-        if: steps.needsRun.outputs.result == 'true'
         uses: gradle/gradle-build-action@v2
       - name: Split tests
-        if: steps.needsRun.outputs.result == 'true'
         id: split-tests
         uses: r7kamura/split-tests-by-timings@v0
         with:
@@ -125,19 +107,16 @@ jobs:
           total: ${{env.total-runners}}
           index: ${{ matrix.runner_index }}
       - name: write out test list
-        if: steps.needsRun.outputs.result == 'true'
         run: echo "${{ steps.split-tests.outputs.paths }}" >> testList.txt
       - name: format gradle args
-        if: steps.needsRun.outputs.result == 'true'
         #regex means: first truncate file paths to align with package name, then swap path delimiter with package delimiter,
         #then drop file extension, then insert --tests option between each.
         run: cat testList.txt | sed -e 's@acceptance-tests/tests/src/test/java/@--tests\ @g;s@/@.@g;s/\.java//g'  > gradleArgs.txt
       - name: run acceptance tests
-        if: steps.needsRun.outputs.result == 'true'
         run: ./gradlew acceptanceTest `cat gradleArgs.txt` -Dorg.gradle.parallel=true -Dorg.gradle.caching=true
       - name: flag failed acceptance tests
         uses: myrotvorets/set-commit-status-action@v2.0.0
-        if: failure() && steps.needsRun.outputs.result == 'true'
+        if: failure()
         with:
           status: ${{ job.status }}
           context: acceptance-tests-${{matrix.runner_index}}
@@ -145,21 +124,19 @@ jobs:
           description: fail acceptance test batch ${{matrix.runner_index}}
       - name: flag passed unit tests
         uses: myrotvorets/set-commit-status-action@v2.0.0
-        if: success() && steps.needsRun.outputs.result == 'true'
+        if: success()
         with:
           status: ${{ job.status }}
           sha: ${{github.pull_request.head.sha}}
       - name: cleanup tempfiles
-        if: steps.needsRun.outputs.result == 'true'
         run: rm testList.txt gradleArgs.txt
       - name: Upload Acceptance Test Results
-        if: steps.needsRun.outputs.result == 'true'
         uses: actions/upload-artifact@v3.1.0
         with:
           name: acceptance-node-${{matrix.runner_index}}-test-results
           path: 'acceptance-tests/tests/build/test-results/acceptanceTest/TEST-*.xml'
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
-        if: steps.needsRun.outputs.result == 'true' && (success() || failure()) # always run even if the build step fails
+        if: (success() || failure()) # always run even if the build step fails
         with:
           report_paths: 'acceptance-tests/tests/build/test-results/acceptanceTest/TEST-*.xml'
